version: 2

updates:
  - directory: /packages/generator-ts-project
    package-ecosystem: npm
    target-branch: dev
    schedule:
      timezone: 05:00 UTC
  - directory: /packages/generator-my-ts-project
    package-ecosystem: npm
    target-branch: dev
    schedule:
        timezone: 05:00 UTC
